apiVersion: apps/v1
kind: Deployment
metadata:
  name: paf-admin-app
  labels:
    app: paf-admin
spec:
  selector:
    matchLabels:
      app: paf-admin
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paf-admin
        tier: app
    spec:
      containers:
      - image: ${IMAGE}
        name: paf-admin-app
        env:
          - name: MYSQL_HOST
            value: paf-admin-mysql
          - name: MYSQL_PORT
            value: '3306'
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: paf-admin-app
                key: mysql_database
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: paf-admin-app
                key: mysql_password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: paf-admin-app
                key: mysql_user
        ports:
        - containerPort: 3333
          name: app