apiVersion: v1
kind: Service
metadata:
  name: paf-admin-app
  labels:
    app: paf-admin
spec:
  ports:
    - port: 3333
  selector:
    app: paf-admin
    tier: app
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pv-claim
  labels:
    app: paf-admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paf-admin-app
  labels:
    app: paf-admin
spec:
  selector:
    matchLabels:
      app: paf-admin
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paf-admin
        tier: app
    spec:
      containers:
      - image: ${IMAGE}
#      - image: paf-admin-app
#        imagePullPolicy: Never
        name: app
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: paf-admin-app
                key: mysql_database
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: paf-admin-app
                key: mysql_password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: paf-admin-app
                key: mysql_user
        ports:
        - containerPort: ${PORT}
#        - containerPort: 3333
          name: app
        volumeMounts:
        - name: app-persistent-storage
          mountPath: /var/www/app
      volumes:
      - name: app-persistent-storage
        persistentVolumeClaim:
          claimName: app-pv-claim
