name: PROD - Build and Deploy

on:
  push:
    branches: master
    tags: releases/v[1-9]+.[0-9]+.[0-9]+

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      # Set environment variables for PROD:
      IMAGE_TAG: paf-admin-app-prod
      K8S_CONTEXT: prod
      SERVER_PORT: 443

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GitHub Container Registry
        id: build
        run: |
          IMAGE="ghcr.io/paf-it/${{ env.IMAGE_TAG }}:${{ github.sha }}"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          docker build --build-arg SERVER_PORT=${{ env.SERVER_PORT }} . --tag ${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_TAG }} $IMAGE
          docker push $IMAGE

      - name: Set kubectl Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.UPCLOUD_KUBECONFIG }}
          context: ${{ env.K8S_CONTEXT }}

      - name: Deploy to Kubernetes
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            k8s/app-configmap.yaml
            k8s/app-service.yaml
            k8s/app-deployment.yaml
          replacement-method: defined
          namespace: ${{ env.K8S_CONTEXT }}
        env:
          IMAGE: ${{ steps.build.outputs.image }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          SERVER_PORT: ${{ env.SERVER_PORT }}
