name: lint-test.yml

on:
  workflow_dispatch

env:
  NODE_VERSION: 'latest'

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Client - Install Dependencies
        working-directory: client
        run: npm ci

      - name: Client - Code Linting
        working-directory: client
        run: npm run lint

      - name: Server - Install Dependencies
        working-directory: server
        run: npm ci

      - name: Server - Code Linting
        working-directory: server
        run: npm run lint
