name: lint-test.yml

on:
  workflow_dispatch

env:
  NODE_VERSION: latest

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Client - Install Dependencies
        run: client/npm ci

      - name: Client - Code Linting
        run: client/npm run lint

      - name: Server - Install Dependencies
        run: server/npm ci

      - name: Server - Code Linting
        run: server/npm run lint
